stages:
  data_collection:
    cmd: python src/data/data_collection.py
    deps:
    - src/data/data_collection.py
    params:
    - data_collection.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data/data_prep.py
    deps:
    - src/data/data_prep.py
    outs:
    - data/processed
  model_building:
    cmd: python src/model/model_building.py
    deps:
    - data/processed
    - src/model/model_building.py
    params:
    - model_building.n_estimators
    outs:
    - models/model.pkl
  model_evaluation:
    cmd: python src/model/model_eval.py
    deps:
    - models/model.pkl
    - src/model/model_eval.py
    outs:
    - reports/metrics.json
